// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200821181350_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            Breed = "Domestic Shorthair",
                            Gender = "Female",
                            Name = "Frankie",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 3,
                            Breed = "Domestic Mediumhair",
                            Gender = "Male",
                            Name = "Jasper",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 8,
                            Breed = "Puggle",
                            Gender = "Female",
                            Name = "Violet",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 5,
                            Breed = "Domestic Longhair",
                            Gender = "Female",
                            Name = "Snugglepuss",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 3,
                            Breed = "Terrier Mix",
                            Gender = "Female",
                            Name = "Ella",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 10,
                            Breed = "Terrier Mix",
                            Gender = "Male",
                            Name = "Huckleberry",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 5,
                            Breed = "Domestic Shorthair",
                            Gender = "Male",
                            Name = "Bubsy",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 7,
                            Breed = "Domestic Shorthair",
                            Gender = "Female",
                            Name = "Toots",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 7,
                            Breed = "Chesapeake Bay Retriever",
                            Gender = "Male",
                            Name = "Rye",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 5,
                            Breed = "Bombay",
                            Gender = "Female",
                            Name = "Scout",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 1,
                            Breed = "Great Dane",
                            Gender = "Male",
                            Name = "Roger",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 6,
                            Breed = "Wolfhound",
                            Gender = "Female",
                            Name = "Fido",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 14,
                            Breed = "Domestic Shorthair",
                            Gender = "Male",
                            Name = "George",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 14,
                            Age = 3,
                            Breed = "Jack Russell Terrier",
                            Gender = "Male",
                            Name = "Russell",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 15,
                            Age = 17,
                            Breed = "Domestic Shorthair",
                            Gender = "Female",
                            Name = "Gypsy",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 16,
                            Age = 4,
                            Breed = "Siamese",
                            Gender = "Male",
                            Name = "Hank",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 17,
                            Age = 5,
                            Breed = "Domestic Shorthair",
                            Gender = "Male",
                            Name = "Jiji",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 18,
                            Age = 1,
                            Breed = "Boxer",
                            Gender = "Male",
                            Name = "Chance",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 19,
                            Age = 8,
                            Breed = "Ragdoll",
                            Gender = "Female",
                            Name = "Sassy",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 20,
                            Age = 12,
                            Breed = "Golden Retriever",
                            Gender = "Male",
                            Name = "Shadow",
                            Species = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
